Repository OpenVisualCloud/Media-Transport-Library, pull requests merged in 2025-07, with the labels that each got.

#1183 Fix: MTL lcore management gets into a bad state
  lib/src/mt_sch.c
Labels: bug fix, review required

#1189 Docs: flex and byacc as required packages for libpcap in build.md
  doc/build.md
Labels: documentation, enhancement, dependencies

#1184 Fix: issue with interpretation of the F bit in the ST40 packet
  lib/src/st2110/st_rx_ancillary_session.c
Labels: bug fix, review required

#1191 Fix: handler return error
  lib/src/st2110/st_rx_video_session.c
Labels: review required

#1198 Fix: incorrect cleanup of the stats alarm handler
  lib/src/mt_stat.c
Labels: bug fix, review required

#1186 Add: support for planar16le
  app/meson.build
  app/perf/meson.build
  app/perf/p16le_to_rfc4175_422be10.c
  app/perf/perf_test.sh
  app/perf/rfc4175_422be10_to_p16le.c
  app/tools/convert_app.c
  app/tools/convert_app_args.c
  app/tools/convert_app_base.h
  include/st_convert_api.h
  include/st_convert_internal.h
  include/st_pipeline_api.h
  lib/src/st2110/pipeline/st20_pipeline_rx.c
  lib/src/st2110/st_avx512.c
  lib/src/st2110/st_avx512.h
  lib/src/st2110/st_convert.c
  lib/src/st2110/st_fmt.c
  lib/src/st2110/st_fmt.h
  plugins/sample/convert_plugin_sample.c
  tests/tools/RxTxApp/src/parse_json.c
  tests/unittest/cvt_test.cpp
Labels: review required, enhancement, help wanted
